
services:
  redis:
    image: redis:7-alpine
    container_name: author_books_redis_container
    restart: always
    command: redis-server --requirepass ${REDIS_PASS}
    environment:
      - REDIS_PASS=${REDIS_PASS}
    ports:
      - "6380:6379"

